version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.dropbox.core:dropbox-core-sdk
    versions:
    - 3.1.5
    - 3.2.0
    - 3.2.1
  - dependency-name: org.json:json
    versions:
    - "20201115"
